//
//  RenderBackend.swift
//  DCRenderKit
//
//  Phase 7 fragment-shader-driven sibling of `ComputeBackend`.
//  Dispatches a `.fusedPixelLocalCluster` node by encoding a
//  full-screen triangle-strip render pass that runs the cluster's
//  fragment shader once. The fragment shader, generated by
//  `MetalSourceBuilder.buildFragmentClusterPipeline`, samples the
//  source texture at each output pixel and chains every member's
//  body call before writing the final colour.
//
//  Phase 7's RenderBackend is deliberately one-cluster-per-pass —
//  it provides the infrastructure that Phase 8's TBDR memoryless
//  routing builds on (chained draws within one render pass +
//  programmable blending) without adding the routing complexity
//  yet. The Phase-7 compute/fragment parity test pins the per-
//  pixel equivalence between this path and `ComputeBackend`.
//

import Foundation
import Metal

/// Render-pipeline dispatch wrapper for fused pixel-local clusters.
@available(iOS 18.0, *)
internal enum RenderBackend {

    /// Errors specific to the render path. Compilation / function-
    /// lookup failures surface from `UberRenderPipelineCache` as
    /// `PipelineError.pipelineState(...)` already; this type covers
    /// the dispatch-time encoder failures.
    enum DispatchError: Error, CustomStringConvertible {
        case unsupportedNodeKind(String)
        case renderEncoderUnavailable

        var description: String {
            switch self {
            case .unsupportedNodeKind(let k):
                return "RenderBackend: node kind \(k) is not supported (only fusedPixelLocalCluster today)"
            case .renderEncoderUnavailable:
                return "RenderBackend: command buffer rejected makeRenderCommandEncoder(descriptor:)"
            }
        }
    }

    /// Execute `node` as a single fragment-shader render pass.
    ///
    /// - Parameters:
    ///   - node: Must be `.fusedPixelLocalCluster` with every member
    ///     using `.pixelLocalOnly` signature shape — same constraint
    ///     `MetalSourceBuilder` enforces for the compute-cluster
    ///     codegen.
    ///   - source: Primary input texture. Bound at `texture(0)` in
    ///     the fragment shader and read by `source.read(gid)`.
    ///   - destination: Render target. Becomes colour attachment 0.
    ///     Must be created with `.renderTarget` usage; the helper
    ///     `validateDestination` surfaces a clear error otherwise.
    ///   - commandBuffer: Caller commits / waits.
    ///   - renderCache: Render PSO cache — defaults to the shared
    ///     instance.
    static func execute(
        node: Node,
        source: MTLTexture,
        destination: MTLTexture,
        commandBuffer: MTLCommandBuffer,
        renderCache: UberRenderPipelineCache = .shared
    ) throws {
        guard case let .fusedPixelLocalCluster(members, wantsLinear, _) = node.kind else {
            throw DispatchError.unsupportedNodeKind(String(describing: node.kind))
        }
        try validateDestination(destination)

        let built = try MetalSourceBuilder.buildFragmentClusterPipeline(
            members: members,
            wantsLinearInput: wantsLinear
        )
        let key = UberRenderPipelineCache.Key(
            vertexFunction: built.vertexFunction,
            fragmentFunction: built.fragmentFunction,
            pixelFormat: destination.pixelFormat
        )
        let cacheHit = renderCache.containsPipelineState(forKey: key)
        let pso = try renderCache.pipelineState(source: built.source, key: key)

        let rpd = MTLRenderPassDescriptor()
        rpd.colorAttachments[0].texture = destination
        rpd.colorAttachments[0].loadAction = .dontCare
        rpd.colorAttachments[0].storeAction = .store

        guard let encoder = commandBuffer.makeRenderCommandEncoder(descriptor: rpd) else {
            throw DispatchError.renderEncoderUnavailable
        }
        encoder.label = "DCR.Fusion.Render.\(built.fragmentFunction)"
        encoder.setRenderPipelineState(pso)

        // Source texture at fragment slot 0; uniforms at fragment
        // buffer slots 0..N-1, one per member.
        encoder.setFragmentTexture(source, index: 0)
        for (index, member) in members.enumerated() {
            try bindFragmentUniform(
                member.uniforms,
                at: index,
                encoder: encoder
            )
        }

        // Full-screen triangle strip — vertex shader fabricates the
        // clip-space positions from `vertex_id` 0..3.
        encoder.drawPrimitives(
            type: .triangleStrip,
            vertexStart: 0,
            vertexCount: 4
        )
        encoder.endEncoding()

        if DCRLogging.diagnosticPipelineLogging {
            DCRLogging.logger.debug(
                "render uber dispatch",
                category: "PipelineBackend",
                attributes: [
                    "fragment": built.fragmentFunction,
                    "nodeLabel": node.debugLabel,
                    "memberCount": "\(members.count)",
                    "cache": cacheHit ? "hit" : "miss",
                ]
            )
        }
    }

    // MARK: - Private helpers

    private static func validateDestination(_ texture: MTLTexture) throws {
        guard texture.usage.contains(.renderTarget) else {
            throw PipelineError.texture(.formatMismatch(
                expected: "destination with .renderTarget usage",
                got: "usage=\(texture.usage.rawValue)"
            ))
        }
    }

    private static func bindFragmentUniform(
        _ uniforms: FilterUniforms,
        at index: Int,
        encoder: MTLRenderCommandEncoder
    ) throws {
        guard uniforms.byteCount > 0 else { return }
        // SDK uniforms are all small POD structs (≤ 64 bytes); the
        // setBytes path stays inside the GPU's transient command-
        // buffer storage. The compute path's 4 KB threshold isn't
        // relevant here.
        var scratch = [UInt8](repeating: 0, count: uniforms.byteCount)
        scratch.withUnsafeMutableBytes { raw in
            uniforms.copyBytes(raw.baseAddress!)
        }
        scratch.withUnsafeBytes { raw in
            encoder.setFragmentBytes(
                raw.baseAddress!,
                length: uniforms.byteCount,
                index: index
            )
        }
    }
}
