//
//  RenderBackend.swift
//  DCRenderKit
//
//  Phase 7 fragment-shader-driven sibling of `ComputeBackend`.
//  Dispatches a `.fusedPixelLocalCluster` node by encoding a
//  full-screen triangle-strip render pass that runs the cluster's
//  fragment shader once. The fragment shader, generated by
//  `MetalSourceBuilder.buildFragmentClusterPipeline`, samples the
//  source texture at each output pixel and chains every member's
//  body call before writing the final colour.
//
//  Phase 7's RenderBackend is deliberately one-cluster-per-pass —
//  it provides the infrastructure that Phase 8's TBDR memoryless
//  routing builds on (chained draws within one render pass +
//  programmable blending) without adding the routing complexity
//  yet. The Phase-7 compute/fragment parity test pins the per-
//  pixel equivalence between this path and `ComputeBackend`.
//

import Foundation
import Metal

/// Render-pipeline dispatch wrapper for fused pixel-local clusters.
@available(iOS 18.0, *)
internal enum RenderBackend {

    /// Errors specific to the render path. Compilation / function-
    /// lookup failures surface from `UberRenderPipelineCache` as
    /// `PipelineError.pipelineState(...)` already; this type covers
    /// the dispatch-time encoder failures.
    enum DispatchError: Error, CustomStringConvertible {
        case unsupportedNodeKind(String)
        case renderEncoderUnavailable

        var description: String {
            switch self {
            case .unsupportedNodeKind(let k):
                return "RenderBackend: node kind \(k) is not supported (only fusedPixelLocalCluster today)"
            case .renderEncoderUnavailable:
                return "RenderBackend: command buffer rejected makeRenderCommandEncoder(descriptor:)"
            }
        }
    }

    /// Execute `node` as a single fragment-shader render pass.
    ///
    /// - Parameters:
    ///   - node: Must be `.fusedPixelLocalCluster` with every member
    ///     using `.pixelLocalOnly` signature shape — same constraint
    ///     `MetalSourceBuilder` enforces for the compute-cluster
    ///     codegen.
    ///   - source: Primary input texture. Bound at `texture(0)` in
    ///     the fragment shader and read by `source.read(gid)`.
    ///   - destination: Render target. Becomes colour attachment 0.
    ///     Must be created with `.renderTarget` usage; the helper
    ///     `validateDestination` surfaces a clear error otherwise.
    ///   - commandBuffer: Caller commits / waits.
    ///   - renderCache: Render PSO cache — defaults to the shared
    ///     instance.
    static func execute(
        node: Node,
        source: MTLTexture,
        destination: MTLTexture,
        commandBuffer: MTLCommandBuffer,
        renderCache: UberRenderPipelineCache = .shared
    ) throws {
        guard case .fusedPixelLocalCluster = node.kind else {
            throw DispatchError.unsupportedNodeKind(String(describing: node.kind))
        }
        try validateDestination(destination)
        try executeChain(
            clusters: [node],
            source: source,
            destination: destination,
            commandBuffer: commandBuffer,
            renderCache: renderCache
        )
    }

    /// Phase 8 chained-cluster dispatch. Encodes a single render
    /// pass with one draw per cluster:
    ///
    ///   - Draw 0 binds the cluster's `_init` fragment, samples the
    ///     primary `source` texture, applies that cluster's bodies,
    ///     and writes the colour attachment.
    ///   - Draws 1..N-1 bind each subsequent cluster's `_chain`
    ///     fragment, which reads the running attachment value via
    ///     programmable blending (`half4 prev [[color(0)]]`),
    ///     applies that cluster's bodies, and writes back to the
    ///     same attachment.
    ///
    /// The TBDR architecture keeps the running attachment in tile
    /// memory across draws, so chaining N clusters needs only ONE
    /// physical render-target texture — `destination` — instead of
    /// the N intermediate textures the per-node compute path would
    /// allocate. That's the Phase-8 memory win.
    ///
    /// - Parameters:
    ///   - clusters: Two or more `.fusedPixelLocalCluster` nodes,
    ///     listed in execution order. Single-element arrays are
    ///     also accepted (degenerate to Phase 7's single-cluster
    ///     case).
    ///   - source: Sampled by draw 0's init fragment; not read by
    ///     subsequent draws.
    ///   - destination: Render target backing the running
    ///     attachment. Must carry `.renderTarget` usage.
    static func executeChain(
        clusters: [Node],
        source: MTLTexture,
        destination: MTLTexture,
        commandBuffer: MTLCommandBuffer,
        renderCache: UberRenderPipelineCache = .shared
    ) throws {
        precondition(!clusters.isEmpty, "executeChain requires at least one cluster")
        try validateDestination(destination)

        let rpd = MTLRenderPassDescriptor()
        rpd.colorAttachments[0].texture = destination
        rpd.colorAttachments[0].loadAction = .dontCare
        rpd.colorAttachments[0].storeAction = .store

        guard let encoder = commandBuffer.makeRenderCommandEncoder(descriptor: rpd) else {
            throw DispatchError.renderEncoderUnavailable
        }
        let chainSummary = clusters.map { $0.debugLabel }.joined(separator: " → ")
        encoder.label = "DCR.Fusion.RenderChain[\(chainSummary)]"

        for (drawIndex, cluster) in clusters.enumerated() {
            let extracted: (members: [FusedClusterMember], wantsLinear: Bool)
            switch cluster.kind {
            case let .fusedPixelLocalCluster(members, wantsLinear, _):
                extracted = (members, wantsLinear)
            case let .pixelLocal(body, uniforms, wantsLinear, _):
                // A single pixel-local node is a degenerate one-
                // member cluster — synthesise the member so the
                // fragment-cluster builder can reuse the same path.
                let synth = FusedClusterMember(
                    body: body,
                    uniforms: uniforms,
                    debugLabel: cluster.debugLabel,
                    additionalRange: 0..<0
                )
                extracted = ([synth], wantsLinear)
            default:
                encoder.endEncoding()
                throw DispatchError.unsupportedNodeKind(String(describing: cluster.kind))
            }
            let members = extracted.members
            let wantsLinear = extracted.wantsLinear

            let built = try MetalSourceBuilder.buildFragmentClusterPipeline(
                members: members,
                wantsLinearInput: wantsLinear
            )
            let variant: MetalSourceBuilder.FragmentClusterVariant =
                (drawIndex == 0) ? .`init` : .chain
            let fragmentFn: String =
                (drawIndex == 0) ? built.initFragmentFunction
                                  : built.chainFragmentFunction
            let key = UberRenderPipelineCache.Key(
                vertexFunction: built.vertexFunction,
                fragmentFunction: fragmentFn,
                pixelFormat: destination.pixelFormat
            )
            let cacheHit = renderCache.containsPipelineState(forKey: key)
            let pso = try renderCache.pipelineState(source: built.source, key: key)
            encoder.setRenderPipelineState(pso)

            // Init draw needs the source texture; chain draws read
            // the running attachment via programmable blending and
            // never bind a fragment texture.
            if drawIndex == 0 {
                encoder.setFragmentTexture(source, index: 0)
            }
            for (uniformIndex, member) in members.enumerated() {
                try bindFragmentUniform(
                    member.uniforms,
                    at: uniformIndex,
                    encoder: encoder
                )
            }

            encoder.drawPrimitives(
                type: .triangleStrip,
                vertexStart: 0,
                vertexCount: 4
            )

            if DCRLogging.diagnosticPipelineLogging {
                DCRLogging.logger.debug(
                    "render chain draw",
                    category: "PipelineBackend",
                    attributes: [
                        "fragment": fragmentFn,
                        "nodeLabel": cluster.debugLabel,
                        "drawIndex": "\(drawIndex)",
                        "variant": (variant == .`init`) ? "init" : "chain",
                        "memberCount": "\(members.count)",
                        "cache": cacheHit ? "hit" : "miss",
                    ]
                )
            }
        }

        encoder.endEncoding()

        if DCRLogging.diagnosticPipelineLogging {
            DCRLogging.logger.debug(
                "render chain dispatched",
                category: "PipelineBackend",
                attributes: [
                    "clusters": "\(clusters.count)",
                    "savedIntermediates": "\(max(clusters.count - 1, 0))",
                ]
            )
        }
    }

    // MARK: - Private helpers

    private static func validateDestination(_ texture: MTLTexture) throws {
        guard texture.usage.contains(.renderTarget) else {
            throw PipelineError.texture(.formatMismatch(
                expected: "destination with .renderTarget usage",
                got: "usage=\(texture.usage.rawValue)"
            ))
        }
    }

    private static func bindFragmentUniform(
        _ uniforms: FilterUniforms,
        at index: Int,
        encoder: MTLRenderCommandEncoder
    ) throws {
        guard uniforms.byteCount > 0 else { return }
        // SDK uniforms are all small POD structs (≤ 64 bytes); the
        // setBytes path stays inside the GPU's transient command-
        // buffer storage. The compute path's 4 KB threshold isn't
        // relevant here.
        var scratch = [UInt8](repeating: 0, count: uniforms.byteCount)
        scratch.withUnsafeMutableBytes { raw in
            uniforms.copyBytes(raw.baseAddress!)
        }
        scratch.withUnsafeBytes { raw in
            encoder.setFragmentBytes(
                raw.baseAddress!,
                length: uniforms.byteCount,
                index: index
            )
        }
    }
}
