//
//  RenderBackend.swift
//  DCRenderKit
//
//  Phase 7 fragment-shader-driven sibling of `ComputeBackend`.
//  Dispatches a `.fusedPixelLocalCluster` node by encoding a
//  full-screen triangle-strip render pass that runs the cluster's
//  fragment shader once. The fragment shader, generated by
//  `MetalSourceBuilder.buildFragmentClusterPipeline`, samples the
//  source texture at each output pixel and chains every member's
//  body call before writing the final colour.
//
//  Phase 7's RenderBackend is deliberately one-cluster-per-pass —
//  it provides the infrastructure that Phase 8's TBDR memoryless
//  routing builds on (chained draws within one render pass +
//  programmable blending) without adding the routing complexity
//  yet. The Phase-7 compute/fragment parity test pins the per-
//  pixel equivalence between this path and `ComputeBackend`.
//

import Foundation
import Metal

/// Render-pipeline dispatch wrapper for fused pixel-local clusters.
@available(iOS 18.0, *)
internal enum RenderBackend {

    /// Errors specific to the render path. Compilation / function-
    /// lookup failures surface from `UberRenderPipelineCache` as
    /// `PipelineError.pipelineState(...)` already; this type covers
    /// the dispatch-time encoder failures.
    enum DispatchError: Error, CustomStringConvertible {
        case unsupportedNodeKind(String)
        case renderEncoderUnavailable

        var description: String {
            switch self {
            case .unsupportedNodeKind(let k):
                return "RenderBackend: node kind \(k) is not supported (only fusedPixelLocalCluster today)"
            case .renderEncoderUnavailable:
                return "RenderBackend: command buffer rejected makeRenderCommandEncoder(descriptor:)"
            }
        }
    }

    /// Execute `node` as a single fragment-shader render pass.
    ///
    /// - Parameters:
    ///   - node: Must be `.fusedPixelLocalCluster` with every member
    ///     using `.pixelLocalOnly` signature shape — same constraint
    ///     `MetalSourceBuilder` enforces for the compute-cluster
    ///     codegen.
    ///   - source: Primary input texture. Bound at `texture(0)` in
    ///     the fragment shader and read by `source.read(gid)`.
    ///   - destination: Render target. Becomes colour attachment 0.
    ///     Must be created with `.renderTarget` usage; the helper
    ///     `validateDestination` surfaces a clear error otherwise.
    ///   - commandBuffer: Caller commits / waits.
    ///   - renderCache: Render PSO cache — defaults to the shared
    ///     instance.
    static func execute(
        node: Node,
        source: MTLTexture,
        destination: MTLTexture,
        commandBuffer: MTLCommandBuffer,
        renderCache: UberRenderPipelineCache = .shared
    ) throws {
        guard case .fusedPixelLocalCluster = node.kind else {
            throw DispatchError.unsupportedNodeKind(String(describing: node.kind))
        }
        try validateDestination(destination)
        try executeChain(
            clusters: [node],
            source: source,
            destination: destination,
            commandBuffer: commandBuffer,
            renderCache: renderCache
        )
    }

    /// Phase 8 chained-cluster dispatch. Encodes a single render
    /// pass with one draw per cluster:
    ///
    ///   - Draw 0 binds the cluster's `_init` fragment, samples the
    ///     primary `source` texture, applies that cluster's bodies,
    ///     and writes the colour attachment.
    ///   - Draws 1..N-1 bind each subsequent cluster's `_chain`
    ///     fragment, which reads the running attachment value via
    ///     programmable blending (`half4 prev [[color(0)]]`),
    ///     applies that cluster's bodies, and writes back to the
    ///     same attachment.
    ///
    /// The TBDR architecture keeps the running attachment in tile
    /// memory across draws, so chaining N clusters needs only ONE
    /// physical render-target texture — `destination` — instead of
    /// the N intermediate textures the per-node compute path would
    /// allocate. That's the Phase-8 memory win.
    ///
    /// - Parameters:
    ///   - clusters: Two or more `.fusedPixelLocalCluster` nodes,
    ///     listed in execution order. Single-element arrays are
    ///     also accepted (degenerate to Phase 7's single-cluster
    ///     case).
    ///   - source: Sampled by draw 0's init fragment; not read by
    ///     subsequent draws.
    ///   - destination: Render target backing the running
    ///     attachment. Must carry `.renderTarget` usage.
    static func executeChain(
        clusters: [Node],
        source: MTLTexture,
        destination: MTLTexture,
        clusterAuxiliaryTextures: [[MTLTexture]] = [],
        commandBuffer: MTLCommandBuffer,
        renderCache: UberRenderPipelineCache = .shared
    ) throws {
        precondition(!clusters.isEmpty, "executeChain requires at least one cluster")
        try validateDestination(destination)

        let rpd = MTLRenderPassDescriptor()
        rpd.colorAttachments[0].texture = destination
        rpd.colorAttachments[0].loadAction = .dontCare
        rpd.colorAttachments[0].storeAction = .store

        guard let encoder = commandBuffer.makeRenderCommandEncoder(descriptor: rpd) else {
            throw DispatchError.renderEncoderUnavailable
        }
        // Metal asserts at encoder dealloc when `endEncoding()` was
        // never called. Several throwing steps in this loop —
        // `MetalSourceBuilder.buildFragmentClusterPipeline`,
        // `renderCache.pipelineState(source:key:)`, and
        // `bindFragmentResources` — can propagate errors without the
        // caller having a chance to call `endEncoding`. The deferred
        // close ends the encoder on every exit path; the trailing
        // `endEncoding()` after the loop sets `encoderEnded` so the
        // defer is a no-op on the success path. Every `throw` below
        // can therefore drop its hand-written `encoder.endEncoding()`
        // pre-amble — `defer` covers all of them uniformly.
        var encoderEnded = false
        defer {
            if !encoderEnded {
                encoder.endEncoding()
            }
        }
        let chainSummary = clusters.map { $0.debugLabel }.joined(separator: " → ")
        encoder.label = "DCR.Fusion.RenderChain[\(chainSummary)]"

        for (drawIndex, cluster) in clusters.enumerated() {
            let extracted: (members: [FusedClusterMember], wantsLinear: Bool)
            switch cluster.kind {
            case let .fusedPixelLocalCluster(members, wantsLinear, _):
                extracted = (members, wantsLinear)
            case let .pixelLocal(body, uniforms, wantsLinear, _):
                let synth = FusedClusterMember(
                    body: body,
                    uniforms: uniforms,
                    debugLabel: cluster.debugLabel,
                    additionalRange: 0..<0
                )
                extracted = ([synth], wantsLinear)
            case let .neighborRead(body, uniforms, _, _):
                guard drawIndex == 0 else {
                    throw DispatchError.unsupportedNodeKind(
                        ".neighborRead can only be the init draw — its body samples source at offsets, which programmable-blending input cannot provide"
                    )
                }
                let synth = FusedClusterMember(
                    body: body,
                    uniforms: uniforms,
                    debugLabel: cluster.debugLabel,
                    additionalRange: 0..<0
                )
                extracted = ([synth], false)
            default:
                throw DispatchError.unsupportedNodeKind(String(describing: cluster.kind))
            }
            let members = extracted.members
            let wantsLinear = extracted.wantsLinear
            let auxTextures: [MTLTexture] =
                drawIndex < clusterAuxiliaryTextures.count
                    ? clusterAuxiliaryTextures[drawIndex]
                    : []

            let built = try MetalSourceBuilder.buildFragmentClusterPipeline(
                members: members,
                wantsLinearInput: wantsLinear
            )
            let isInit = (drawIndex == 0)
            let fragmentFn: String
            if isInit {
                fragmentFn = built.initFragmentFunction
            } else {
                guard let chainFn = built.chainFragmentFunction else {
                    throw DispatchError.unsupportedNodeKind(
                        "shape \(built.signatureShape) has no chain variant; cannot occupy non-init position"
                    )
                }
                fragmentFn = chainFn
            }
            let variant: MetalSourceBuilder.FragmentClusterVariant =
                isInit ? .`init` : .chain

            let key = UberRenderPipelineCache.Key(
                vertexFunction: built.vertexFunction,
                fragmentFunction: fragmentFn,
                pixelFormat: destination.pixelFormat
            )
            let cacheHit = renderCache.containsPipelineState(forKey: key)
            let pso = try renderCache.pipelineState(source: built.source, key: key)
            encoder.setRenderPipelineState(pso)

            try bindFragmentResources(
                shape: built.signatureShape,
                isInit: isInit,
                source: source,
                members: members,
                auxTextures: auxTextures,
                destination: destination,
                encoder: encoder
            )

            encoder.drawPrimitives(
                type: .triangleStrip,
                vertexStart: 0,
                vertexCount: 4
            )

            if DCRLogging.diagnosticPipelineLogging {
                DCRLogging.logger.debug(
                    "render chain draw",
                    category: "PipelineBackend",
                    attributes: [
                        "fragment": fragmentFn,
                        "nodeLabel": cluster.debugLabel,
                        "drawIndex": "\(drawIndex)",
                        "variant": (variant == .`init`) ? "init" : "chain",
                        "shape": Self.shapeTag(built.signatureShape),
                        "memberCount": "\(members.count)",
                        "auxCount": "\(auxTextures.count)",
                        "cache": cacheHit ? "hit" : "miss",
                    ]
                )
            }
        }

        encoder.endEncoding()
        encoderEnded = true

        if DCRLogging.diagnosticPipelineLogging {
            DCRLogging.logger.debug(
                "render chain dispatched",
                category: "PipelineBackend",
                attributes: [
                    "clusters": "\(clusters.count)",
                    "savedIntermediates": "\(max(clusters.count - 1, 0))",
                ]
            )
        }
    }

    /// Bind fragment textures + per-member uniforms + (NormalBlend
    /// only) the destination dimensions, per the codegen's slot
    /// conventions. Texture slots are pinned by
    /// `MetalSourceBuilder.buildFragmentClusterPipeline`.
    private static func bindFragmentResources(
        shape: FusionBodySignatureShape,
        isInit: Bool,
        source: MTLTexture,
        members: [FusedClusterMember],
        auxTextures: [MTLTexture],
        destination: MTLTexture,
        encoder: MTLRenderCommandEncoder
    ) throws {
        switch shape {
        case .pixelLocalOnly:
            if isInit {
                encoder.setFragmentTexture(source, index: 0)
            }

        case .pixelLocalWithLUT3D:
            guard let lut = auxTextures.first else {
                throw DispatchError.unsupportedNodeKind(
                    ".pixelLocalWithLUT3D requires an aux LUT texture; got 0"
                )
            }
            if isInit {
                encoder.setFragmentTexture(source, index: 0)
                encoder.setFragmentTexture(lut, index: 1)
            } else {
                encoder.setFragmentTexture(lut, index: 0)
            }

        case .pixelLocalWithOverlay:
            guard let overlay = auxTextures.first else {
                throw DispatchError.unsupportedNodeKind(
                    ".pixelLocalWithOverlay requires an aux overlay texture; got 0"
                )
            }
            if isInit {
                encoder.setFragmentTexture(source, index: 0)
                encoder.setFragmentTexture(overlay, index: 1)
            } else {
                encoder.setFragmentTexture(overlay, index: 0)
            }

        case .neighborReadWithSource:
            // Init only — caller already enforces.
            encoder.setFragmentTexture(source, index: 0)

        case .pixelLocalWithGid:
            throw DispatchError.unsupportedNodeKind(
                ".pixelLocalWithGid has no fragment codegen yet"
            )
        }

        for (index, member) in members.enumerated() {
            try bindFragmentUniform(
                member.uniforms,
                at: index,
                encoder: encoder
            )
        }

        if shape == .pixelLocalWithOverlay {
            // NormalBlend's body needs `outputSize` (uint2) to map
            // overlay coordinates to destination pixel space. The
            // codegen wires it as a buffer at slot members.count;
            // values come from the destination's dimensions.
            var size = SIMD2<UInt32>(
                UInt32(destination.width),
                UInt32(destination.height)
            )
            withUnsafeBytes(of: &size) { raw in
                encoder.setFragmentBytes(
                    raw.baseAddress!,
                    length: MemoryLayout<SIMD2<UInt32>>.size,
                    index: members.count
                )
            }
        }
    }

    /// Compact tag for a signature shape, used in diagnostic logs.
    private static func shapeTag(_ shape: FusionBodySignatureShape) -> String {
        switch shape {
        case .pixelLocalOnly:         return "pxlOnly"
        case .pixelLocalWithGid:      return "pxlGid"
        case .pixelLocalWithLUT3D:    return "lut3D"
        case .pixelLocalWithOverlay:  return "overlay"
        case .neighborReadWithSource: return "neighborRead"
        }
    }

    // MARK: - Private helpers

    private static func validateDestination(_ texture: MTLTexture) throws {
        guard texture.usage.contains(.renderTarget) else {
            throw PipelineError.texture(.formatMismatch(
                expected: "destination with .renderTarget usage",
                got: "usage=\(texture.usage.rawValue)"
            ))
        }
    }

    private static func bindFragmentUniform(
        _ uniforms: FilterUniforms,
        at index: Int,
        encoder: MTLRenderCommandEncoder
    ) throws {
        guard uniforms.byteCount > 0 else { return }
        // SDK uniforms are all small POD structs (≤ 64 bytes); the
        // setBytes path stays inside the GPU's transient command-
        // buffer storage. The compute path's 4 KB threshold isn't
        // relevant here.
        var scratch = [UInt8](repeating: 0, count: uniforms.byteCount)
        scratch.withUnsafeMutableBytes { raw in
            uniforms.copyBytes(raw.baseAddress!)
        }
        scratch.withUnsafeBytes { raw in
            encoder.setFragmentBytes(
                raw.baseAddress!,
                length: uniforms.byteCount,
                index: index
            )
        }
    }
}
