//
//  LegacyParityTests.swift
//  DCRenderKitTests
//
//  Phase-3 step 5 — the pixel-level parity gate. For every
//  `.pixelLocalOnly`-shape filter that the compute backend can
//  codegen, this file runs the filter twice against a known input
//  texture:
//
//    1. Via the legacy kernel (`DCRLegacy<Name>Filter`) — the
//       byte-for-byte copy of the pre-refactor production kernel
//       frozen in `Tests/DCRenderKitTests/LegacyKernels/`.
//    2. Via `ComputeBackend.execute(...)` — the runtime uber
//       kernel generated by `MetalSourceBuilder`.
//
//  The test asserts the two outputs are equal within ±1 LSB in
//  BGRA8 (the Float16 rounding floor for a single round of
//  read→math→write). Any drift past that margin means codegen has
//  altered the per-pixel semantics and Phase 5 cannot ship.
//
//  Why this gate matters: method B of the `docs/pipeline-compiler-
//  design.md` decision means production has no standalone kernel
//  fallback in Phase 5. If Phase 3's uber kernels diverge from the
//  frozen legacy references, every pixel DCR ships changes
//  silently. This file is the tripwire that catches that.
//

import XCTest
import Metal
@testable import DCRenderKit

@available(iOS 18.0, *)
final class LegacyParityTests: XCTestCase {

    private var device: MTLDevice!
    private var queue: MTLCommandQueue!

    override func setUpWithError() throws {
        guard let dev = MTLCreateSystemDefaultDevice() else {
            throw XCTSkip("Metal device unavailable")
        }
        guard let q = dev.makeCommandQueue() else {
            throw XCTSkip("Metal command queue unavailable")
        }
        device = dev
        queue = q
        do {
            try LegacyKernelFixture.registerIfNeeded()
        } catch LegacyKernelFixture.Error.metalDeviceUnavailable {
            throw XCTSkip("Metal device unavailable for legacy fixture")
        }
    }

    // MARK: - The seven pure pixelLocalOnly filters

    /// Parity for Exposure at three slider values covering
    /// identity, negative (linear gain), and positive (Reinhard
    /// tonemap). At +50 the bright branch is exercised; at -50 the
    /// negative branch.
    func testExposureParityAcrossSliders() throws {
        try runParity(
            legacyKernel: "DCRLegacyExposureFilter",
            filters: [ExposureFilter(exposure: 0),
                      ExposureFilter(exposure: 50),
                      ExposureFilter(exposure: -50)]
        )
    }

    /// Contrast at identity + ±50 — exercises the DaVinci log-slope
    /// with the default scene `lumaMean = 0.5`.
    func testContrastParityAcrossSliders() throws {
        try runParity(
            legacyKernel: "DCRLegacyContrastFilter",
            filters: [ContrastFilter(contrast: 0, lumaMean: 0.5),
                      ContrastFilter(contrast: 50, lumaMean: 0.5),
                      ContrastFilter(contrast: -50, lumaMean: 0.5)]
        )
    }

    /// Blacks (Reinhard toe) at identity + ±50.
    func testBlacksParityAcrossSliders() throws {
        try runParity(
            legacyKernel: "DCRLegacyBlacksFilter",
            filters: [BlacksFilter(blacks: 0),
                      BlacksFilter(blacks: 50),
                      BlacksFilter(blacks: -50)]
        )
    }

    /// Whites (Filmic shoulder) at identity + ±50.
    func testWhitesParityAcrossSliders() throws {
        try runParity(
            legacyKernel: "DCRLegacyWhitesFilter",
            filters: [WhitesFilter(whites: 0),
                      WhitesFilter(whites: 50),
                      WhitesFilter(whites: -50)]
        )
    }

    /// Saturation at 1.0 identity, 0.0 full desaturate, 1.5 boost.
    /// Exercises the OKLCh round-trip + gamut clamp.
    func testSaturationParityAcrossSliders() throws {
        try runParity(
            legacyKernel: "DCRLegacySaturationFilter",
            filters: [SaturationFilter(saturation: 1.0),
                      SaturationFilter(saturation: 0.0),
                      SaturationFilter(saturation: 1.5)]
        )
    }

    /// Vibrance at identity + ±0.5 — exercises the low-C boost
    /// gate and skin-hue protection.
    func testVibranceParityAcrossSliders() throws {
        try runParity(
            legacyKernel: "DCRLegacyVibranceFilter",
            filters: [VibranceFilter(vibrance: 0.0),
                      VibranceFilter(vibrance: 0.5),
                      VibranceFilter(vibrance: -0.5)]
        )
    }

    /// WhiteBalance at default (5500 K neutral + tint 0) + warm /
    /// cool shifts.
    func testWhiteBalanceParityAcrossSliders() throws {
        try runParity(
            legacyKernel: "DCRLegacyWhiteBalanceFilter",
            filters: [WhiteBalanceFilter(temperature: 5500, tint: 0),
                      WhiteBalanceFilter(temperature: 7000, tint: 50),
                      WhiteBalanceFilter(temperature: 4500, tint: -50)]
        )
    }

    // MARK: - Parity runner

    /// Core parity test: for every filter in `filters`, dispatch
    /// it twice — once via the frozen legacy kernel, once via the
    /// codegen path — and assert every BGRA8 channel agrees to
    /// within `tolerance`.
    private func runParity(
        legacyKernel: String,
        filters: [any FilterProtocol],
        tolerance: Int = 1,
        file: StaticString = #filePath,
        line: UInt = #line
    ) throws {
        let input = makeRamp256x1()
        let isolatedUberCache = UberKernelCache(device: .shared)

        for filter in filters {
            let legacyOut = try allocateOutputLike(input)
            let codegenOut = try allocateOutputLike(input)

            // 1. Run via legacy kernel (bypass ComputeBackend;
            //    use the standalone ComputeDispatcher path).
            let cbLegacy = queue.makeCommandBuffer()!
            try ComputeDispatcher.dispatch(
                kernel: legacyKernel,
                uniforms: filter.uniforms,
                additionalInputs: filter.additionalInputs,
                source: input,
                destination: legacyOut,
                commandBuffer: cbLegacy
            )
            cbLegacy.commit()
            cbLegacy.waitUntilCompleted()

            // 2. Run via the codegen backend.
            let node = try singleNode(for: filter)
            let cbCodegen = queue.makeCommandBuffer()!
            try ComputeBackend.execute(
                node: node,
                source: input,
                destination: codegenOut,
                commandBuffer: cbCodegen,
                uberCache: isolatedUberCache
            )
            cbCodegen.commit()
            cbCodegen.waitUntilCompleted()

            // 3. Compare pixel-by-pixel.
            let legacyBytes = readBGRA8(legacyOut)
            let codegenBytes = readBGRA8(codegenOut)
            XCTAssertEqual(
                legacyBytes.count, codegenBytes.count,
                "Texture dimensions mismatch for \(type(of: filter))",
                file: file, line: line
            )

            var worstDelta = 0
            var worstIndex = -1
            for i in 0..<legacyBytes.count {
                let d = abs(Int(legacyBytes[i]) - Int(codegenBytes[i]))
                if d > worstDelta {
                    worstDelta = d
                    worstIndex = i
                }
            }

            XCTAssertLessThanOrEqual(
                worstDelta, tolerance,
                "\(type(of: filter)) uber kernel drifts ±\(worstDelta) LSB from legacy at index \(worstIndex) — expected ≤ \(tolerance)",
                file: file, line: line
            )
        }
    }

    // MARK: - Fixture helpers

    private func singleNode(for filter: any FilterProtocol) throws -> Node {
        let graph = try XCTUnwrap(Lowering.lower(
            [.single(filter)],
            source: TextureInfo(width: 256, height: 1, pixelFormat: .rgba16Float)
        ))
        return graph.nodes[0]
    }

    /// 256×1 horizontal BGRA ramp — every 8-bit value appears once.
    /// Fair coverage of the input domain without needing a
    /// 256×256 photo fixture.
    private func makeRamp256x1() -> MTLTexture {
        let desc = MTLTextureDescriptor.texture2DDescriptor(
            pixelFormat: .bgra8Unorm,
            width: 256, height: 1,
            mipmapped: false
        )
        desc.usage = [.shaderRead, .shaderWrite]
        let tex = device.makeTexture(descriptor: desc)!
        var bytes = [UInt8](repeating: 0, count: 256 * 4)
        for x in 0..<256 {
            // Slight channel variation so filters that treat R/G/B
            // differently (WhiteBalance, Saturation) get non-trivial
            // inputs. Each channel gets a different phase of the
            // ramp.
            bytes[x * 4 + 0] = UInt8(x)                            // B
            bytes[x * 4 + 1] = UInt8((x + 85) % 256)               // G
            bytes[x * 4 + 2] = UInt8((x + 170) % 256)              // R
            bytes[x * 4 + 3] = 255                                 // A
        }
        bytes.withUnsafeBytes { raw in
            tex.replace(
                region: MTLRegionMake2D(0, 0, 256, 1),
                mipmapLevel: 0,
                withBytes: raw.baseAddress!,
                bytesPerRow: 256 * 4
            )
        }
        return tex
    }

    private func allocateOutputLike(_ other: MTLTexture) throws -> MTLTexture {
        let desc = MTLTextureDescriptor.texture2DDescriptor(
            pixelFormat: .bgra8Unorm,
            width: other.width, height: other.height,
            mipmapped: false
        )
        desc.usage = [.shaderRead, .shaderWrite]
        guard let tex = device.makeTexture(descriptor: desc) else {
            throw XCTSkip("Unable to allocate output texture")
        }
        return tex
    }

    private func readBGRA8(_ texture: MTLTexture) -> [UInt8] {
        var bytes = [UInt8](repeating: 0, count: texture.width * texture.height * 4)
        bytes.withUnsafeMutableBytes { raw in
            texture.getBytes(
                raw.baseAddress!,
                bytesPerRow: texture.width * 4,
                from: MTLRegionMake2D(0, 0, texture.width, texture.height),
                mipmapLevel: 0
            )
        }
        return bytes
    }
}
